language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest coveralls"
  - "git config --global user.email 'user@test.com'"
  - "git config --global user.name 'Test User'"
script:
  coverage run --source=seed runtests.py
after_success:
  coveralls
