language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest coveralls collective.dist"
  - "git config --global user.email 'user@test.com'"
  - "git config --global user.name 'Test User'"
  - 'echo "[server-login]\nusername:testuser\npassword:testpass" > ~/.pypirc'
  - "touch .nocleanup"
script:
  coverage run -p --source=seed runtests.py
after_success:
  - coverage combine
  - coveralls debug
  - coveralls
